language: node_js
node_js:
  - "0.8"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar &"
  - sleep 3 # give some time to bind to sockets, etc
before_script:
  - npm install -g grunt-cli
  - npm install grunt grunt-contrib-jshint grunt-contrib-uglify grunt-webdriver grunt-contrib-connect
script: grunt -v
